# Pull blue ocean image
FROM jenkins/jenkins


# Build the container
USER root

# install wget
RUN apt-get update
RUN apt-get install -y wget iputils-ping

# get maven 3.2.2
RUN wget --no-verbose -O /tmp/apache-maven-3.8.5-src.tar.gz https://dlcdn.apache.org/maven/maven-3/3.8.5/source/apache-maven-3.8.5-src.tar.gz
# verify checksum
# RUN echo "35c39251d2af99b6624d40d801f6ff02 /tmp/apache-maven-3.4.0-bin.tar.gz" | md5sum -c

# install maven
RUN tar xzf /tmp/apache-maven-3.8.5-src.tar.gz -C /opt/
RUN ln -s /opt/apache-maven-3.8.5 /opt/maven
RUN ln -s /opt/maven/bin/mvn /usr/local/bin
RUN rm -f /tmp/apache-maven-3.8.5-bin.tar.gz
ENV MAVEN_HOME /opt/maven

RUN chown -R jenkins:jenkins /opt/maven

# remove download archive files
RUN apt-get clean

USER jenkins

RUN jenkins-plugin-cli --plugins "blueocean:1.25.3 docker-workflow:1.28"