version: '3'

services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
        - '1025:1025'
        - '8025:8025'
  jenkins:
    build:
      context: ./docker/base
      dockerfile: dockerfile
    image: base/jenkins
    ports:
        - '8080:8080'
        - '50000:50000'
    volumes:
      - './data/jenkins_home:/var/jenkins_home'
  jenkins_dind:
    build:
      context: ./docker/dind
      dockerfile: dockerfile
    image: dind/jenkins
    user: root
    ports:
        - '8181:8080'
        - '51111:50000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './data/dind/jenkins_home:/var/jenkins_home'             
